# Generated by Django 5.2.7 on 2025-10-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='stadiums.stadium'),
        ),
    ]
