# Generated by Django 5.2.7 on 2025-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_alter_stadium_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
