# Generated by Django 5.2.7 on 2025-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0004_stadium_latitude_stadium_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='size',
            field=models.IntegerField(blank=True),
        ),
    ]
