# Generated by Django 5.2.7 on 2025-10-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0005_stadium_avg_rating_alter_stadium_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='avg_rating',
        ),
    ]
