# Generated by Django 5.2.7 on 2025-10-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
