# Generated by Django 5.2.7 on 2025-10-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='stadiums.stadium'),
        ),
    ]
