# Generated by Django 5.2.7 on 2025-10-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(choices=[('Payme', 'payme'), ('Click', 'click')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking')),
            ],
        ),
    ]
